DROP DATABASE Company ;
CREATE DATABASE Company;
USE Company;

CREATE TABLE Customer(
        CustID VARCHAR(6) NOT NULL ,
        NIC VARCHAR (15) NOT NULL  ,
        Name VARCHAR(20) NOT NULL ,
        Tel INT NOT NULL ,
        CONSTRAINT PRIMARY KEY (CustID)
);

CREATE TABLE Bus(
	BusID VARCHAR(6) NOT NULL,
	SeatCount INT NOT NULL,
	OperatorID VARCHAR(6) NOT NULL,
	OwnerID VARCHAR(6) NOT NULL,
	CONSTRAINT PRIMARY KEY (BusID)
);

CREATE TABLE Seat(
        SeatID VARCHAR(6) NOT NULL ,
        BusID VARCHAR (50) ,
        Status VARCHAR(1) NOT NULL,
        CONSTRAINT PRIMARY KEY (SeatID,BusID)
);

CREATE TABLE ReservationDetails(
	ReservationID VARCHAR(6) NOT NULL,
	SeatID VARCHAR(3) NOT NULL,
	BusID VARCHAR(3) NOT NULL,
	CustID VARCHAR(6) NOT NULL,
	NIC VARCHAR(15) NOT NULL,
	CONSTRAINT PRIMARY KEY (ReservationID),
	CONSTRAINT FOREIGN KEY(CustID) REFERENCES Customer(CustID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(BusID) REFERENCES Bus(BusID)
    ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FOREIGN KEY(SeatID) REFERENCES Seat(SeatID)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Operator(
        OperatorID VARCHAR(6) NOT NULL ,
        BusID VARCHAR (6)  NOT NULL,
        Name VARCHAR(20) ,
        CONSTRAINT PRIMARY KEY (OperatorID),
        CONSTRAINT FOREIGN KEY(BusID) REFERENCES Bus(BusID)
        ON UPDATE CASCADE ON DELETE CASCADE
);



